/**
 * add-puzzles-v2.ts  — +30 питань на кожного боса (разом буде 50)
 * Запуск: bun add-puzzles-v2.ts
 */
import { prisma } from './src/lib/prisma';
import crypto from 'crypto';

type PuzzleData = {
  title: string;
  description: string;
  type: 'SORTING' | 'MULTIPLE_CHOICE';
  correctOrder: string;
  blocks: { id: string; text: string }[];
};

function resolveIds(puzzles: PuzzleData[]): PuzzleData[] {
  return puzzles.map(p => {
    const idMap = new Map<string, string>();
    const blocks = p.blocks.map(b => {
      const newId = crypto.randomUUID();
      idMap.set(b.id, newId);
      return { ...b, id: newId };
    });
    const correctOrder = p.correctOrder.split(',').map(id => idMap.get(id) ?? id).join(',');
    return { ...p, blocks, correctOrder };
  });
}

// ─────────────────────────────────────────────────────────────────
// Бос 1: Зелений Жнець — 30 нових питань (разом 50)
// ─────────────────────────────────────────────────────────────────
const reaper30: PuzzleData[] = [
  { title: 'Рейд 21: Array Buffer витік', description: 'Яка структура даних у браузері НЕ збирається GC поки Worker тримає референс?', type: 'MULTIPLE_CHOICE', correctOrder: 'rv2-1-B', blocks: [{ id: 'rv2-1-A', text: 'A. LocalStorage' }, { id: 'rv2-1-B', text: 'B. SharedArrayBuffer' }, { id: 'rv2-1-C', text: 'C. IndexedDB запис' }, { id: 'rv2-1-D', text: 'D. Cookie' }] },
  { title: 'Рейд 22: LRU Cache', description: 'Склади LRU-кеш на 2 елементи без витоку пам\'яті:', type: 'SORTING', correctOrder: 'rv2-2-1,rv2-2-2,rv2-2-3,rv2-2-4', blocks: [{ id: 'rv2-2-1', text: 'const cache = new Map();' }, { id: 'rv2-2-2', text: 'function lru(key, val) {' }, { id: 'rv2-2-3', text: '  if (cache.size >= 2) cache.delete(cache.keys().next().value);' }, { id: 'rv2-2-4', text: '  cache.set(key, val); }' }] },
  { title: 'Рейд 23: Object.create витік', description: 'Що трапляється з прототипним ланцюжком при Object.create(bigObj)?', type: 'MULTIPLE_CHOICE', correctOrder: 'rv2-3-A', blocks: [{ id: 'rv2-3-A', text: 'A. bigObj залишається в пам\'яті через прототипний ланцюжок' }, { id: 'rv2-3-B', text: 'B. bigObj копіюється у новий об\'єкт' }, { id: 'rv2-3-C', text: 'C. bigObj одразу збирається GC' }, { id: 'rv2-3-D', text: 'D. Помилка: Object.create не приймає складні об\'єкти' }] },
  { title: 'Рейд 24: React Context витік', description: 'Яка причина витоку при великому Context value?', type: 'MULTIPLE_CHOICE', correctOrder: 'rv2-4-C', blocks: [{ id: 'rv2-4-A', text: 'A. Context не підтримує великі об\'єкти' }, { id: 'rv2-4-B', text: 'B. Context автоматично видаляється при unmount' }, { id: 'rv2-4-C', text: 'C. Всі споживачі Context тримають посилання на весь value об\'єкт' }, { id: 'rv2-4-D', text: 'D. Context зберігається у localStorage' }] },
  { title: 'Рейд 25: Symbol як ключ', description: 'Склади WeakMap з Symbol ключем для приватних даних:', type: 'SORTING', correctOrder: 'rv2-5-1,rv2-5-2,rv2-5-3', blocks: [{ id: 'rv2-5-1', text: 'const _private = new WeakMap();' }, { id: 'rv2-5-2', text: 'class Foo { constructor() { _private.set(this, { secret: 42 }); } }' }, { id: 'rv2-5-3', text: 'const getSecret = (obj) => _private.get(obj).secret;' }] },
  { title: 'Рейд 26: Node.js global витік', description: 'Як глобальна змінна у Node.js спричиняє витік?', type: 'MULTIPLE_CHOICE', correctOrder: 'rv2-6-B', blocks: [{ id: 'rv2-6-A', text: 'A. Node.js автоматично очищає global об\'єкт' }, { id: 'rv2-6-B', text: 'B. Глобальні змінні живуть увесь час процесу і ніколи не збираються GC' }, { id: 'rv2-6-C', text: 'C. global обмежений 10 МБ' }, { id: 'rv2-6-D', text: 'D. Змінні у global копіюються при кожному запиті' }] },
  { title: 'Рейд 27: MutationObserver cleanup', description: 'Склади код відключення MutationObserver при розмонтуванні:', type: 'SORTING', correctOrder: 'rv2-7-1,rv2-7-2,rv2-7-3,rv2-7-4', blocks: [{ id: 'rv2-7-1', text: 'const observer = new MutationObserver(callback);' }, { id: 'rv2-7-2', text: 'observer.observe(target, { childList: true });' }, { id: 'rv2-7-3', text: 'return () => {' }, { id: 'rv2-7-4', text: '  observer.disconnect(); };' }] },
  { title: 'Рейд 28: Circular reference', description: 'Чому JSON.stringify викине помилку при circular reference?', type: 'MULTIPLE_CHOICE', correctOrder: 'rv2-8-A', blocks: [{ id: 'rv2-8-A', text: 'A. JSON не підтримує циклічні посилання — воно нескінченно рекурсує' }, { id: 'rv2-8-B', text: 'B. JSON автоматично обрізає циклічні посилання' }, { id: 'rv2-8-C', text: 'C. Тільки якщо об\'єкт більше 1 МБ' }, { id: 'rv2-8-D', text: 'D. JSON.stringify ніколи не кидає помилок' }] },
  { title: 'Рейд 29: performance.memory', description: 'Що вимірює performance.memory.usedJSHeapSize?', type: 'MULTIPLE_CHOICE', correctOrder: 'rv2-9-C', blocks: [{ id: 'rv2-9-A', text: 'A. Загальна RAM сторінки' }, { id: 'rv2-9-B', text: 'B. Розмір CSS в пам\'яті' }, { id: 'rv2-9-C', text: 'C. Обсяг пам\'яті, який використовує V8 heap для JavaScript об\'єктів' }, { id: 'rv2-9-D', text: 'D. Розмір завантажених зображень' }] },
  { title: 'Рейд 30: Cache-Control заголовок', description: 'Склади Express middleware що кешує відповідь на 1 годину:', type: 'SORTING', correctOrder: 'rv2-10-1,rv2-10-2,rv2-10-3', blocks: [{ id: 'rv2-10-1', text: 'app.use((req, res, next) => {' }, { id: 'rv2-10-2', text: "  res.setHeader('Cache-Control', 'public, max-age=3600');" }, { id: 'rv2-10-3', text: '  next(); });' }] },
  { title: 'Рейд 31: Symbol.iterator витік', description: 'Що небезпечно у нескінченному кастомному ітераторі?', type: 'MULTIPLE_CHOICE', correctOrder: 'rv2-11-B', blocks: [{ id: 'rv2-11-A', text: 'A. Symbol.iterator несумісний з for...of' }, { id: 'rv2-11-B', text: 'B. for...of тримає ітератор у пам\'яті поки не завершиться — нескінченний ітератор ніколи не звільниться' }, { id: 'rv2-11-C', text: 'C. Ітератори автоматично зупиняються через 1 сек' }, { id: 'rv2-11-D', text: 'D. Немає різниці між кінченим і нескінченним ітератором' }] },
  { title: 'Рейд 32: URL.createObjectURL', description: 'Склади код правильного звільнення blob URL:', type: 'SORTING', correctOrder: 'rv2-12-1,rv2-12-2,rv2-12-3,rv2-12-4', blocks: [{ id: 'rv2-12-1', text: 'const blob = new Blob([data]);' }, { id: 'rv2-12-2', text: 'const url = URL.createObjectURL(blob);' }, { id: 'rv2-12-3', text: 'img.src = url;' }, { id: 'rv2-12-4', text: 'img.onload = () => URL.revokeObjectURL(url);' }] },
  { title: 'Рейд 33: Redux витік', description: 'Чому зберігання великих blob/ArrayBuffer у Redux store є поганою практикою?', type: 'MULTIPLE_CHOICE', correctOrder: 'rv2-13-D', blocks: [{ id: 'rv2-13-A', text: 'A. Redux не підтримує бінарні дані' }, { id: 'rv2-13-B', text: 'B. Redux автоматично обмежує розмір store до 5 МБ' }, { id: 'rv2-13-C', text: 'C. Бінарні дані сповільнюють Redux DevTools' }, { id: 'rv2-13-D', text: 'D. Store зберігається в пам\'яті весь час роботи застосунку — великі дані живуть до unmount store' }] },
  { title: 'Рейд 34: Proxy та витік', description: 'Склади Proxy що відстежує доступ без витоку (без збереження цільового об\'єкта):', type: 'SORTING', correctOrder: 'rv2-14-1,rv2-14-2,rv2-14-3', blocks: [{ id: 'rv2-14-1', text: 'function trackAccess(target) {' }, { id: 'rv2-14-2', text: '  return new Proxy(target, { get(obj, key) { log(key); return obj[key]; } });' }, { id: 'rv2-14-3', text: '  // target звільниться коли proxy стане недосяжним\n}' }] },
  { title: 'Рейд 35: V8 hidden classes', description: 'Що таке "hidden class" у V8 і як вони впливають на пам\'ять?', type: 'MULTIPLE_CHOICE', correctOrder: 'rv2-15-A', blocks: [{ id: 'rv2-15-A', text: 'A. V8 створює приховані класи для оптимізації. Динамічне додавання властивостей заважає оптимізації і збільшує споживання пам\'яті' }, { id: 'rv2-15-B', text: 'B. Hidden classes — це CSS класи приховані від JS' }, { id: 'rv2-15-C', text: 'C. Приховані класи завжди видаляються GC' }, { id: 'rv2-15-D', text: 'D. V8 не використовує hidden classes після ES6' }] },
  { title: 'Рейд 36: Worker cleanup', description: 'Що потрібно зробити з Web Worker після завершення роботи?', type: 'MULTIPLE_CHOICE', correctOrder: 'rv2-16-C', blocks: [{ id: 'rv2-16-A', text: 'A. Worker автоматично завершується' }, { id: 'rv2-16-B', text: 'B. Викликати worker.close()' }, { id: 'rv2-16-C', text: 'C. Викликати worker.terminate()' }, { id: 'rv2-16-D', text: 'D. Worker очищається при reload сторінки' }] },
  { title: 'Рейд 37: setInterval у класі', description: 'Склади клас з таймером без витоку:', type: 'SORTING', correctOrder: 'rv2-17-1,rv2-17-2,rv2-17-3,rv2-17-4', blocks: [{ id: 'rv2-17-1', text: 'class Timer {' }, { id: 'rv2-17-2', text: '  start() { this._id = setInterval(() => this.tick(), 1000); }' }, { id: 'rv2-17-3', text: '  stop() { clearInterval(this._id); }' }, { id: 'rv2-17-4', text: '}' }] },
  { title: 'Рейд 38: Node.js process.on витік', description: 'Чому додавання process.on("exit") у кожному запиті спричинює витік?', type: 'MULTIPLE_CHOICE', correctOrder: 'rv2-18-B', blocks: [{ id: 'rv2-18-A', text: 'A. process.on не дозволений у обробниках запитів' }, { id: 'rv2-18-B', text: 'B. EventEmitter має ліміт слухачів (10 за замовч.) — при перевищенні попередження і всі слухачі залишаються в пам\'яті' }, { id: 'rv2-18-C', text: 'C. process автоматично видаляє exit слухачів' }, { id: 'rv2-18-D', text: 'D. Немає різниці' }] },
  { title: 'Рейд 39: Zustand persist витік', description: 'Що треба зробити при незбереженні великих об\'єктів у Zustand persist?', type: 'MULTIPLE_CHOICE', correctOrder: 'rv2-19-D', blocks: [{ id: 'rv2-19-A', text: 'A. Вимкнути Zustand DevTools' }, { id: 'rv2-19-B', text: 'B. Використати sessionStorage замість localStorage' }, { id: 'rv2-19-C', text: 'C. Збільшити розмір localStorage' }, { id: 'rv2-19-D', text: 'D. Використати partialize щоб зберігати тільки необхідні поля, а не весь state' }] },
  { title: 'Рейд 40: Closure + async витік', description: 'Склади async функцію яка НЕ тримає великий масив у замиканні після завершення:', type: 'SORTING', correctOrder: 'rv2-20-1,rv2-20-2,rv2-20-3,rv2-20-4', blocks: [{ id: 'rv2-20-1', text: 'async function process() {' }, { id: 'rv2-20-2', text: '  const bigData = await fetchData();' }, { id: 'rv2-20-3', text: '  const result = compute(bigData);' }, { id: 'rv2-20-4', text: '  return result; // bigData не захоплюється в замиканні\n}' }] },
  { title: 'Рейд 41: Lazy loading', description: 'Яка техніка зменшує початкове споживання пам\'яті у React застосунках?', type: 'MULTIPLE_CHOICE', correctOrder: 'rv2-21-A', blocks: [{ id: 'rv2-21-A', text: 'A. React.lazy + Suspense для code splitting — завантажує компоненти лише при потребі' }, { id: 'rv2-21-B', text: 'B. Збереження компонентів у localStorage' }, { id: 'rv2-21-C', text: 'C. Рендеринг всіх маршрутів у прихованих div' }, { id: 'rv2-21-D', text: 'D. Inline стилі замість CSS класів' }] },
  { title: 'Рейд 42: IndexedDB cleanup', description: 'Склади код видалення застарілих записів з IndexedDB:', type: 'SORTING', correctOrder: 'rv2-22-1,rv2-22-2,rv2-22-3', blocks: [{ id: 'rv2-22-1', text: 'const tx = db.transaction("store", "readwrite");' }, { id: 'rv2-22-2', text: 'const store = tx.objectStore("store");' }, { id: 'rv2-22-3', text: 'store.delete(oldKey);' }] },
  { title: 'Рейд 43: V8 старе покоління', description: 'Що таке "old generation" у V8 garbage collector?', type: 'MULTIPLE_CHOICE', correctOrder: 'rv2-23-B', blocks: [{ id: 'rv2-23-A', text: 'A. Об\'єкти старші за 30 секунд' }, { id: 'rv2-23-B', text: 'B. Об\'єкти що пережили кілька minor GC циклів і переміщені у довготривалу область пам\'яті' }, { id: 'rv2-23-C', text: 'C. Прототипний ланцюжок Object' }, { id: 'rv2-23-D', text: 'D. ES5 функції без стрілок' }] },
  { title: 'Рейд 44: Реактивний cleanup', description: 'Що повертає useEffect для cleanup великого підписки?', type: 'MULTIPLE_CHOICE', correctOrder: 'rv2-24-C', blocks: [{ id: 'rv2-24-A', text: 'A. null' }, { id: 'rv2-24-B', text: 'B. Promise з cleanup' }, { id: 'rv2-24-C', text: 'C. Функцію що викликається при unmount або зміні залежностей' }, { id: 'rv2-24-D', text: 'D. Boolean false' }] },
  { title: 'Рейд 45: Стрімінг відповіді', description: 'Склади Express маршрут що стрімить файл без завантаження у пам\'ять:', type: 'SORTING', correctOrder: 'rv2-25-1,rv2-25-2,rv2-25-3', blocks: [{ id: 'rv2-25-1', text: 'app.get("/file", (req, res) => {' }, { id: 'rv2-25-2', text: '  const stream = fs.createReadStream("./big.csv");' }, { id: 'rv2-25-3', text: '  stream.pipe(res); });' }] },
  { title: 'Рейд 46: AbortSignal cascade', description: 'Як пов\'язати AbortSignal з вкладеними fetch запитами?', type: 'MULTIPLE_CHOICE', correctOrder: 'rv2-26-D', blocks: [{ id: 'rv2-26-A', text: 'A. Передати той самий signal у кожен fetch' }, { id: 'rv2-26-B', text: 'B. Використати Promise.all + signal' }, { id: 'rv2-26-C', text: 'C. AbortController скасовує всі fetch автоматично' }, { id: 'rv2-26-D', text: 'D. Передати { signal } у кожен fetch — скасування контролера зупинить всі вкладені запити' }] },
  { title: 'Рейд 47: GC примусово', description: 'Як запустити GC у Node.js для тестування (не для продакшну)?', type: 'MULTIPLE_CHOICE', correctOrder: 'rv2-27-A', blocks: [{ id: 'rv2-27-A', text: 'A. node --expose-gc → global.gc()' }, { id: 'rv2-27-B', text: 'B. process.gc()' }, { id: 'rv2-27-C', text: 'C. require("gc").collect()' }, { id: 'rv2-27-D', text: 'D. GC не можна запустити вручну' }] },
  { title: 'Рейд 48: Canvas витік', description: 'Склади код очищення Canvas без витоку пам\'яті:', type: 'SORTING', correctOrder: 'rv2-28-1,rv2-28-2,rv2-28-3', blocks: [{ id: 'rv2-28-1', text: 'const ctx = canvas.getContext("2d");' }, { id: 'rv2-28-2', text: 'ctx.clearRect(0, 0, canvas.width, canvas.height);' }, { id: 'rv2-28-3', text: '// При видаленні: canvas.width = 0; canvas.height = 0;' }] },
  { title: 'Рейд 49: Closure loop класика', description: 'Чому var у циклі спричиняє проблему замикання?\n\nfor (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 0);\n}\n// Виведе: ???', type: 'MULTIPLE_CHOICE', correctOrder: 'rv2-29-C', blocks: [{ id: 'rv2-29-A', text: 'A. 0, 1, 2' }, { id: 'rv2-29-B', text: 'B. undefined, undefined, undefined' }, { id: 'rv2-29-C', text: 'C. 3, 3, 3 (var має function scope — всі callback бачать один i=3)' }, { id: 'rv2-29-D', text: 'D. Помилка ReferenceError' }] },
  { title: 'Рейд 50: Фінальний бій', description: 'Назви три найпоширеніші причини memory leaks у SPA (Single Page Application):', type: 'MULTIPLE_CHOICE', correctOrder: 'rv2-30-D', blocks: [{ id: 'rv2-30-A', text: 'A. Великі зображення, повільний сервер, старий браузер' }, { id: 'rv2-30-B', text: 'B. Відсутність TypeScript, погані імена змінних, відсутність коментарів' }, { id: 'rv2-30-C', text: 'C. Webpack, Babel, Node.js' }, { id: 'rv2-30-D', text: 'D. EventListener без cleanup, setInterval без clearInterval, відписки від store/subscriptions без відписки при unmount' }] },
];

// ─────────────────────────────────────────────────────────────────
// Бос 2: Уроборос — 30 нових питань
// ─────────────────────────────────────────────────────────────────
const dragon30: PuzzleData[] = [
  { title: 'Рейд 21: Promise chain', description: 'Що поверне цей код?\nPromise.resolve(1).then(v => v + 1).then(v => v * 2)', type: 'MULTIPLE_CHOICE', correctOrder: 'dv2-1-C', blocks: [{ id: 'dv2-1-A', text: 'A. Promise<1>' }, { id: 'dv2-1-B', text: 'B. 3' }, { id: 'dv2-1-C', text: 'C. Promise<4>' }, { id: 'dv2-1-D', text: 'D. NaN' }] },
  { title: 'Рейд 22: Fibonacci DP', description: 'Склади динамічне програмування для Fibonacci (O(n) пам\'яті → O(1)):', type: 'SORTING', correctOrder: 'dv2-2-1,dv2-2-2,dv2-2-3,dv2-2-4', blocks: [{ id: 'dv2-2-1', text: 'function fib(n) {' }, { id: 'dv2-2-2', text: '  let [a, b] = [0, 1];' }, { id: 'dv2-2-3', text: '  for (let i = 2; i <= n; i++) [a, b] = [b, a + b];' }, { id: 'dv2-2-4', text: '  return b; }' }] },
  { title: 'Рейд 23: Event Loop фаза', description: 'В якій фазі Event Loop виконуються колбеки setImmediate (Node.js)?', type: 'MULTIPLE_CHOICE', correctOrder: 'dv2-3-B', blocks: [{ id: 'dv2-3-A', text: 'A. Timers (разом з setTimeout)' }, { id: 'dv2-3-B', text: 'B. Check (після poll фази)' }, { id: 'dv2-3-C', text: 'C. Microtask queue' }, { id: 'dv2-3-D', text: 'D. Close callbacks' }] },
  { title: 'Рейд 24: Stack Overflow захист', description: 'Як безпечно обробити глибоко вкладені дані (1000+ рівнів) без stack overflow?', type: 'MULTIPLE_CHOICE', correctOrder: 'dv2-4-D', blocks: [{ id: 'dv2-4-A', text: 'A. Збільшити --stack-size у Node.js' }, { id: 'dv2-4-B', text: 'B. Використати рекурсію з try/catch' }, { id: 'dv2-4-C', text: 'C. Розбити на чанки через setTimeout' }, { id: 'dv2-4-D', text: 'D. Ітеративний обхід з явним стеком (масив/черга) замість рекурсії' }] },
  { title: 'Рейд 25: async/await помилка', description: 'Склади правильний try/catch для паралельних async операцій:', type: 'SORTING', correctOrder: 'dv2-5-1,dv2-5-2,dv2-5-3,dv2-5-4', blocks: [{ id: 'dv2-5-1', text: 'try {' }, { id: 'dv2-5-2', text: '  const [a, b] = await Promise.all([fetchA(), fetchB()]);' }, { id: 'dv2-5-3', text: '  process(a, b);' }, { id: 'dv2-5-4', text: '} catch (err) { handleError(err); }' }] },
  { title: 'Рейд 26: Topological Sort', description: 'Для чого використовують топологічне сортування у програмуванні?', type: 'MULTIPLE_CHOICE', correctOrder: 'dv2-6-A', blocks: [{ id: 'dv2-6-A', text: 'A. Визначення порядку залежностей у DAG (наприклад, task scheduling, imports)' }, { id: 'dv2-6-B', text: 'B. Сортування масивів за значенням' }, { id: 'dv2-6-C', text: 'C. Пошук найкоротшого шляху' }, { id: 'dv2-6-D', text: 'D. Балансування бінарного дерева' }] },
  { title: 'Рейд 27: Generator повернення', description: 'Що поверне виклик gen.return("done") на незавершеному generator?', type: 'MULTIPLE_CHOICE', correctOrder: 'dv2-7-C', blocks: [{ id: 'dv2-7-A', text: 'A. Помилка TypeError' }, { id: 'dv2-7-B', text: 'B. { value: undefined, done: false }' }, { id: 'dv2-7-C', text: 'C. { value: "done", done: true }' }, { id: 'dv2-7-D', text: 'D. Generator продовжить виконання' }] },
  { title: 'Рейд 28: Async Queue', description: 'Склади просту async чергу що виконує задачі послідовно:', type: 'SORTING', correctOrder: 'dv2-8-1,dv2-8-2,dv2-8-3,dv2-8-4', blocks: [{ id: 'dv2-8-1', text: 'let queue = Promise.resolve();' }, { id: 'dv2-8-2', text: 'function enqueue(task) {' }, { id: 'dv2-8-3', text: '  queue = queue.then(() => task());' }, { id: 'dv2-8-4', text: '  return queue; }' }] },
  { title: 'Рейд 29: while(true) з yield', description: 'Чому while(true) у Generator безпечний, а у звичайній функції — ні?', type: 'MULTIPLE_CHOICE', correctOrder: 'dv2-9-B', blocks: [{ id: 'dv2-9-A', text: 'A. Generator обмежений 1000 ітераціями' }, { id: 'dv2-9-B', text: 'B. yield призупиняє виконання і повертає контроль — виконання відновлюється тільки при наступному .next()' }, { id: 'dv2-9-C', text: 'C. Generator виконується у окремому потоці' }, { id: 'dv2-9-D', text: 'D. Різниці немає' }] },
  { title: 'Рейд 30: Flood Fill алгоритм', description: 'Склади ітеративний Flood Fill без рекурсії (уникнення stack overflow):', type: 'SORTING', correctOrder: 'dv2-10-1,dv2-10-2,dv2-10-3,dv2-10-4', blocks: [{ id: 'dv2-10-1', text: 'function floodFill(grid, r, c, color) {' }, { id: 'dv2-10-2', text: '  const stack = [[r, c]];' }, { id: 'dv2-10-3', text: '  while (stack.length) { const [x, y] = stack.pop(); if (!valid(x, y)) continue;' }, { id: 'dv2-10-4', text: '    grid[x][y] = color; stack.push([x+1,y],[x-1,y],[x,y+1],[x,y-1]); } }' }] },
  { title: 'Рейд 31: Promise.any', description: 'Чим Promise.any відрізняється від Promise.race?', type: 'MULTIPLE_CHOICE', correctOrder: 'dv2-11-D', blocks: [{ id: 'dv2-11-A', text: 'A. Promise.any повільніший' }, { id: 'dv2-11-B', text: 'B. Promise.race ігнорує помилки' }, { id: 'dv2-11-C', text: 'C. Різниці немає' }, { id: 'dv2-11-D', text: 'D. Promise.any повертає перший УСПІШНИЙ результат, ігноруючи відхилення. Promise.race повертає перший (успіх або помилку)' }] },
  { title: 'Рейд 32: Linked List цикл', description: 'Склади алгоритм Floyd для виявлення циклу у Linked List:', type: 'SORTING', correctOrder: 'dv2-12-1,dv2-12-2,dv2-12-3,dv2-12-4', blocks: [{ id: 'dv2-12-1', text: 'let slow = head, fast = head;' }, { id: 'dv2-12-2', text: 'while (fast && fast.next) {' }, { id: 'dv2-12-3', text: '  slow = slow.next; fast = fast.next.next;' }, { id: 'dv2-12-4', text: '  if (slow === fast) return true; }\nreturn false;' }] },
  { title: 'Рейд 33: Microtask черга', description: 'Скільки разів виконається .then якщо всередині нього кидати Promise.resolve?', type: 'MULTIPLE_CHOICE', correctOrder: 'dv2-13-C', blocks: [{ id: 'dv2-13-A', text: 'A. Нескінченно (stack overflow)' }, { id: 'dv2-13-B', text: 'B. Тільки один раз' }, { id: 'dv2-13-C', text: 'C. Стільки разів скільки вкладених Promise — кожен додається в microtask queue' }, { id: 'dv2-13-D', text: 'D. Залежить від браузера' }] },
  { title: 'Рейд 34: Parallelism у Node.js', description: 'Як досягнути справжнього паралелізму (CPU) у Node.js?', type: 'MULTIPLE_CHOICE', correctOrder: 'dv2-14-A', blocks: [{ id: 'dv2-14-A', text: 'A. Worker Threads — кожен Worker має власний V8 інстанс і event loop' }, { id: 'dv2-14-B', text: 'B. async/await автоматично паралелізує CPU задачі' }, { id: 'dv2-14-C', text: 'C. cluster.fork() виконує задачі в одному потоці' }, { id: 'dv2-14-D', text: 'D. Promise.all виконує callback паралельно' }] },
  { title: 'Рейд 35: Два вказівники', description: 'Склади алгоритм знаходження суми двох чисел рівної target (Two Sum, O(n)):', type: 'SORTING', correctOrder: 'dv2-15-1,dv2-15-2,dv2-15-3,dv2-15-4', blocks: [{ id: 'dv2-15-1', text: 'function twoSum(nums, target) {' }, { id: 'dv2-15-2', text: '  const map = new Map();' }, { id: 'dv2-15-3', text: '  for (let i = 0; i < nums.length; i++) {' }, { id: 'dv2-15-4', text: '    if (map.has(target - nums[i])) return [map.get(target-nums[i]), i];\n    map.set(nums[i], i); } }' }] },
  { title: 'Рейд 36: Async Iterator з пагінацією', description: 'Що повертає async generator при кожному yield?', type: 'MULTIPLE_CHOICE', correctOrder: 'dv2-16-B', blocks: [{ id: 'dv2-16-A', text: 'A. Синхронне значення' }, { id: 'dv2-16-B', text: 'B. Promise<{ value, done }>' }, { id: 'dv2-16-C', text: 'C. Observable' }, { id: 'dv2-16-D', text: 'D. Iterator без Promise' }] },
  { title: 'Рейд 37: Concurrency limit', description: 'Склади функцію що виконує не більше 3 промісів паралельно:', type: 'SORTING', correctOrder: 'dv2-17-1,dv2-17-2,dv2-17-3,dv2-17-4', blocks: [{ id: 'dv2-17-1', text: 'async function limitedAll(tasks, limit = 3) {' }, { id: 'dv2-17-2', text: '  const results = [];' }, { id: 'dv2-17-3', text: '  for (let i = 0; i < tasks.length; i += limit) {' }, { id: 'dv2-17-4', text: '    results.push(...await Promise.all(tasks.slice(i, i+limit).map(t => t())));\n  }\n  return results; }' }] },
  { title: 'Рейд 38: Хвостовий виклик JS', description: 'Чи підтримує V8 (Chrome/Node.js) tail call optimization у strict mode?', type: 'MULTIPLE_CHOICE', correctOrder: 'dv2-18-C', blocks: [{ id: 'dv2-18-A', text: 'A. Так, повністю для всіх функцій' }, { id: 'dv2-18-B', text: 'B. Тільки для arrow functions' }, { id: 'dv2-18-C', text: 'C. Ні — V8 видалив підтримку TCO у 2017, незважаючи на специфікацію ES6' }, { id: 'dv2-18-D', text: 'D. Так, але тільки для генераторів' }] },
  { title: 'Рейд 39: Backpressure', description: 'Що таке backpressure у Node.js Streams?', type: 'MULTIPLE_CHOICE', correctOrder: 'dv2-19-A', blocks: [{ id: 'dv2-19-A', text: 'A. Механізм зупинки читання якщо writable не встигає обробляти — запобігає переповненню пам\'яті' }, { id: 'dv2-19-B', text: 'B. Помилка мережі при slow connection' }, { id: 'dv2-19-C', text: 'C. Автоматичне стиснення даних' }, { id: 'dv2-19-D', text: 'D. Reverse proxy налаштування' }] },
  { title: 'Рейд 40: Memoization decorator', description: 'Склади memoize декоратор для будь-якої функції:', type: 'SORTING', correctOrder: 'dv2-20-1,dv2-20-2,dv2-20-3,dv2-20-4', blocks: [{ id: 'dv2-20-1', text: 'function memoize(fn) {' }, { id: 'dv2-20-2', text: '  const cache = new Map();' }, { id: 'dv2-20-3', text: '  return (...args) => {' }, { id: 'dv2-20-4', text: '    const key = JSON.stringify(args);\n    if (!cache.has(key)) cache.set(key, fn(...args));\n    return cache.get(key); }; }' }] },
  { title: 'Рейд 41: BigO рекурсії', description: 'Яка складність наївного рекурсивного Fibonacci?', type: 'MULTIPLE_CHOICE', correctOrder: 'dv2-21-D', blocks: [{ id: 'dv2-21-A', text: 'A. O(n)' }, { id: 'dv2-21-B', text: 'B. O(n log n)' }, { id: 'dv2-21-C', text: 'C. O(n²)' }, { id: 'dv2-21-D', text: 'D. O(2^n) — кожен виклик породжує два нові' }] },
  { title: 'Рейд 42: Debounce реалізація', description: 'Склади debounce функцію:', type: 'SORTING', correctOrder: 'dv2-22-1,dv2-22-2,dv2-22-3,dv2-22-4', blocks: [{ id: 'dv2-22-1', text: 'function debounce(fn, delay) {' }, { id: 'dv2-22-2', text: '  let timer;' }, { id: 'dv2-22-3', text: '  return (...args) => {' }, { id: 'dv2-22-4', text: '    clearTimeout(timer);\n    timer = setTimeout(() => fn(...args), delay); }; }' }] },
  { title: 'Рейд 43: Observer pattern', description: 'Яку проблему вирішує паттерн Observer (EventEmitter)?', type: 'MULTIPLE_CHOICE', correctOrder: 'dv2-23-B', blocks: [{ id: 'dv2-23-A', text: 'A. Зменшення кількості HTTP запитів' }, { id: 'dv2-23-B', text: 'B. Розв\'язання (decoupling) між суб\'єктом і споживачами — суб\'єкт не знає хто на нього підписаний' }, { id: 'dv2-23-C', text: 'C. Кешування відповідей сервера' }, { id: 'dv2-23-D', text: 'D. Синхронізація між Worker Threads' }] },
  { title: 'Рейд 44: Throttle vs Debounce', description: 'Коли краще використовувати throttle замість debounce?', type: 'MULTIPLE_CHOICE', correctOrder: 'dv2-24-C', blocks: [{ id: 'dv2-24-A', text: 'A. При пошуковому вводі' }, { id: 'dv2-24-B', text: 'B. При відправці форм' }, { id: 'dv2-24-C', text: 'C. При scroll/mousemove — коли потрібне регулярне виконання під час тривалих подій, а не тільки після паузи' }, { id: 'dv2-24-D', text: 'D. При завантаженні файлів' }] },
  { title: 'Рейд 45: Binary Search', description: 'Склади бінарний пошук у відсортованому масиві:', type: 'SORTING', correctOrder: 'dv2-25-1,dv2-25-2,dv2-25-3,dv2-25-4', blocks: [{ id: 'dv2-25-1', text: 'function bsearch(arr, target) {' }, { id: 'dv2-25-2', text: '  let lo = 0, hi = arr.length - 1;' }, { id: 'dv2-25-3', text: '  while (lo <= hi) { const mid = (lo + hi) >> 1;' }, { id: 'dv2-25-4', text: '    if (arr[mid] === target) return mid;\n    arr[mid] < target ? lo = mid+1 : hi = mid-1; }\n  return -1; }' }] },
  { title: 'Рейд 46: Event delegation', description: 'Яка перевага event delegation перед прямими слухачами на кожному елементі?', type: 'MULTIPLE_CHOICE', correctOrder: 'dv2-26-A', blocks: [{ id: 'dv2-26-A', text: 'A. Один слухач на батьківському елементі замість тисяч на дочірніх — менше пам\'яті і автоматична підтримка динамічних елементів' }, { id: 'dv2-26-B', text: 'B. Event delegation швидший у 10 разів' }, { id: 'dv2-26-C', text: 'C. Захист від XSS' }, { id: 'dv2-26-D', text: 'D. Підтримка тільки click подій' }] },
  { title: 'Рейд 47: queueMicrotask', description: 'Коли слід використовувати queueMicrotask замість setTimeout(fn, 0)?', type: 'MULTIPLE_CHOICE', correctOrder: 'dv2-27-B', blocks: [{ id: 'dv2-27-A', text: 'A. Ніколи — setTimeout(fn,0) завжди кращий' }, { id: 'dv2-27-B', text: 'B. Коли потрібно виконати код після поточного synchronous коду, але ДО наступного макрозавдання і перемальовування' }, { id: 'dv2-27-C', text: 'C. Для анімацій' }, { id: 'dv2-27-D', text: 'D. Вони ідентичні' }] },
  { title: 'Рейд 48: Promise.withResolvers', description: 'Що нового дає Promise.withResolvers() (ES2024)?', type: 'MULTIPLE_CHOICE', correctOrder: 'dv2-28-D', blocks: [{ id: 'dv2-28-A', text: 'A. Автоматичний timeout для Promise' }, { id: 'dv2-28-B', text: 'B. Promise з вбудованим retry' }, { id: 'dv2-28-C', text: 'C. Ланцюгування без .then' }, { id: 'dv2-28-D', text: 'D. Повертає { promise, resolve, reject } — дозволяє resolve/reject ззовні без конструктора' }] },
  { title: 'Рейд 49: Ітеративний DFS', description: 'Склади ітеративний DFS обхід дерева (без рекурсії):', type: 'SORTING', correctOrder: 'dv2-29-1,dv2-29-2,dv2-29-3,dv2-29-4', blocks: [{ id: 'dv2-29-1', text: 'function dfs(root) { const stack = [root];' }, { id: 'dv2-29-2', text: '  while (stack.length) {' }, { id: 'dv2-29-3', text: '    const node = stack.pop();' }, { id: 'dv2-29-4', text: '    visit(node);\n    if (node.right) stack.push(node.right);\n    if (node.left) stack.push(node.left); } }' }] },
  { title: 'Рейд 50: Фінальний бій Уробороса', description: 'Яке головне правило event loop: коли виконуються microtasks (Promise)?', type: 'MULTIPLE_CHOICE', correctOrder: 'dv2-30-A', blocks: [{ id: 'dv2-30-A', text: 'A. Після кожного macrotask (setTimeout, I/O) — перед наступним macrotask весь microtask queue спустошується' }, { id: 'dv2-30-B', text: 'B. Одночасно з macrotasks' }, { id: 'dv2-30-C', text: 'C. Тільки при idle стані браузера' }, { id: 'dv2-30-D', text: 'D. Раз на 16мс разом з requestAnimationFrame' }] },
];

// ─────────────────────────────────────────────────────────────────
// Бос 3: Червоний Демон — 30 нових питань
// ─────────────────────────────────────────────────────────────────
const demon30: PuzzleData[] = [
  { title: 'Рейд 21: Brute Force атака', description: 'Яка стратегія захищає від brute force атак на логін?', type: 'MULTIPLE_CHOICE', correctOrder: 'dmv2-1-D', blocks: [{ id: 'dmv2-1-A', text: 'A. Довгий пароль адміна' }, { id: 'dmv2-1-B', text: 'B. HTTPS протокол' }, { id: 'dmv2-1-C', text: 'C. Велика БД' }, { id: 'dmv2-1-D', text: 'D. Account lockout після N невдалих спроб + rate limiting + CAPTCHA' }] },
  { title: 'Рейд 22: Зберігання сесій', description: 'Склади безпечне збереження JWT у HttpOnly cookie при логіні:', type: 'SORTING', correctOrder: 'dmv2-2-1,dmv2-2-2,dmv2-2-3', blocks: [{ id: 'dmv2-2-1', text: 'const token = jwt.sign({ id: user.id }, JWT_SECRET, { expiresIn: "7d" });' }, { id: 'dmv2-2-2', text: "res.cookie('token', token, { httpOnly: true, secure: true, sameSite: 'strict' });" }, { id: 'dmv2-2-3', text: 'res.json({ success: true });' }] },
  { title: 'Рейд 23: CORS налаштування', description: 'Яке CORS налаштування є найбезпечнішим для API?', type: 'MULTIPLE_CHOICE', correctOrder: 'dmv2-3-B', blocks: [{ id: 'dmv2-3-A', text: 'A. Access-Control-Allow-Origin: *' }, { id: 'dmv2-3-B', text: 'B. Whitelist конкретних доменів + credentials: true тільки для них' }, { id: 'dmv2-3-C', text: 'C. Відключити CORS повністю' }, { id: 'dmv2-3-D', text: 'D. Allow всіх із Authorization заголовком' }] },
  { title: 'Рейд 24: Input sanitization', description: 'Склади Express middleware для санітизації HTML вводу:', type: 'SORTING', correctOrder: 'dmv2-4-1,dmv2-4-2,dmv2-4-3', blocks: [{ id: 'dmv2-4-1', text: 'import { escape } from "html-escaper";' }, { id: 'dmv2-4-2', text: 'app.use((req, res, next) => {' }, { id: 'dmv2-4-3', text: '  if (req.body?.content) req.body.content = escape(req.body.content);\n  next(); });' }] },
  { title: 'Рейд 25: Path traversal', description: 'Що таке Path Traversal атака (../../../etc/passwd)?', type: 'MULTIPLE_CHOICE', correctOrder: 'dmv2-5-A', blocks: [{ id: 'dmv2-5-A', text: 'A. Вихід за межі дозволеного каталогу через "../" у шляху файлу — доступ до системних файлів' }, { id: 'dmv2-5-B', text: 'B. SQL запит до системних таблиць' }, { id: 'dmv2-5-C', text: 'C. XSS через URL параметри' }, { id: 'dmv2-5-D', text: 'D. Перевантаження файлової системи' }] },
  { title: 'Рейд 26: Idempotency', description: 'Яка HTTP операція є idempotent (повторний виклик дає той самий результат)?', type: 'MULTIPLE_CHOICE', correctOrder: 'dmv2-6-C', blocks: [{ id: 'dmv2-6-A', text: 'A. POST' }, { id: 'dmv2-6-B', text: 'B. PATCH' }, { id: 'dmv2-6-C', text: 'C. DELETE та GET — DELETE видаляє один раз, GET лише читає' }, { id: 'dmv2-6-D', text: 'D. Жодна' }] },
  { title: 'Рейд 27: Argon2 vs bcrypt', description: 'Чому Argon2 кращий за bcrypt для хешування паролів у 2024?', type: 'MULTIPLE_CHOICE', correctOrder: 'dmv2-7-B', blocks: [{ id: 'dmv2-7-A', text: 'A. Argon2 швидший за bcrypt' }, { id: 'dmv2-7-B', text: 'B. Argon2 використовує більше пам\'яті (memory-hard), що захищає від GPU/ASIC атак краще' }, { id: 'dmv2-7-C', text: 'C. bcrypt застарів і не підтримується' }, { id: 'dmv2-7-D', text: 'D. Різниці немає' }] },
  { title: 'Рейд 28: Zod validation', description: 'Склади Zod схему для безпечного логіну:', type: 'SORTING', correctOrder: 'dmv2-8-1,dmv2-8-2,dmv2-8-3', blocks: [{ id: 'dmv2-8-1', text: 'const loginSchema = z.object({' }, { id: 'dmv2-8-2', text: '  email: z.string().email(),\n  password: z.string().min(8).max(72),' }, { id: 'dmv2-8-3', text: '});' }] },
  { title: 'Рейд 29: Zero-trust архітектура', description: 'Який принцип Zero-Trust архітектури?', type: 'MULTIPLE_CHOICE', correctOrder: 'dmv2-9-D', blocks: [{ id: 'dmv2-9-A', text: 'A. Довіряти всім у внутрішній мережі' }, { id: 'dmv2-9-B', text: 'B. Дозволити тільки HTTPS трафік' }, { id: 'dmv2-9-C', text: 'C. Вимкнути зовнішній доступ до API' }, { id: 'dmv2-9-D', text: 'D. "Never trust, always verify" — кожен запит автентифікується незалежно від мережі' }] },
  { title: 'Рейд 30: Audit log', description: 'Склади Express middleware для логування чутливих дій:', type: 'SORTING', correctOrder: 'dmv2-10-1,dmv2-10-2,dmv2-10-3,dmv2-10-4', blocks: [{ id: 'dmv2-10-1', text: 'app.use("/admin", (req, res, next) => {' }, { id: 'dmv2-10-2', text: '  const log = { user: req.user?.id, path: req.path, time: new Date() };' }, { id: 'dmv2-10-3', text: '  auditLogger.info(log);' }, { id: 'dmv2-10-4', text: '  next(); });' }] },
  { title: 'Рейд 31: Replay attack', description: 'Як JWT захищається від replay attack (повторного використання старого токена)?', type: 'MULTIPLE_CHOICE', correctOrder: 'dmv2-11-A', blocks: [{ id: 'dmv2-11-A', text: 'A. Short expiry (15хв) + refresh token rotation — старий refresh token інвалідується після використання' }, { id: 'dmv2-11-B', text: 'B. HTTPS шифрує токен автоматично' }, { id: 'dmv2-11-C', text: 'C. JWT підпис унікальний — повторне використання неможливе' }, { id: 'dmv2-11-D', text: 'D. Достатньо довгого секрету' }] },
  { title: 'Рейд 32: Environment secrets', description: 'Де ЗАБОРОНЕНО зберігати API ключі та паролі?', type: 'MULTIPLE_CHOICE', correctOrder: 'dmv2-12-C', blocks: [{ id: 'dmv2-12-A', text: 'A. .env файл (у .gitignore)' }, { id: 'dmv2-12-B', text: 'B. Render Environment Variables' }, { id: 'dmv2-12-C', text: 'C. У Git репозиторії (навіть приватному) або у клієнтському JS коді' }, { id: 'dmv2-12-D', text: 'D. AWS Secrets Manager' }] },
  { title: 'Рейд 33: Subdomain takeover', description: 'Що таке Subdomain Takeover атака?', type: 'MULTIPLE_CHOICE', correctOrder: 'dmv2-13-B', blocks: [{ id: 'dmv2-13-A', text: 'A. DDoS атака через субдомени' }, { id: 'dmv2-13-B', text: 'B. DNS запис вказує на видалений сервіс — зловмисник реєструє той самий сервіс і перехоплює трафік субдомену' }, { id: 'dmv2-13-C', text: 'C. SQL Injection через URL' }, { id: 'dmv2-13-D', text: 'D. Витік cookie через субдомен' }] },
  { title: 'Рейд 34: API versioning безпека', description: 'Чому важливо вимикати старі версії API?', type: 'MULTIPLE_CHOICE', correctOrder: 'dmv2-14-D', blocks: [{ id: 'dmv2-14-A', text: 'A. Старі версії повільніші' }, { id: 'dmv2-14-B', text: 'B. Для SEO оптимізації' }, { id: 'dmv2-14-C', text: 'C. Зменшення розміру коду' }, { id: 'dmv2-14-D', text: 'D. Старі endpoints часто не мають патчів безпеки і стають вектором атаки' }] },
  { title: 'Рейд 35: Prepared Statement Prisma', description: 'Склади Prisma запит стійкий до SQL Injection:', type: 'SORTING', correctOrder: 'dmv2-15-1,dmv2-15-2,dmv2-15-3', blocks: [{ id: 'dmv2-15-1', text: 'const email = req.body.email;' }, { id: 'dmv2-15-2', text: '// НЕ правильно: prisma.$queryRawUnsafe(`SELECT * FROM User WHERE email = "${email}"`);' }, { id: 'dmv2-15-3', text: '// Правильно:\nconst user = await prisma.user.findUnique({ where: { email } });' }] },
  { title: 'Рейд 36: Security headers', description: 'Який заголовок захищає від Clickjacking атак?', type: 'MULTIPLE_CHOICE', correctOrder: 'dmv2-16-A', blocks: [{ id: 'dmv2-16-A', text: 'A. X-Frame-Options: DENY (або CSP frame-ancestors \'none\')' }, { id: 'dmv2-16-B', text: 'B. X-XSS-Protection: 1' }, { id: 'dmv2-16-C', text: 'C. Strict-Transport-Security' }, { id: 'dmv2-16-D', text: 'D. Content-Type: application/json' }] },
  { title: 'Рейд 37: Mass Assignment', description: 'Що таке Mass Assignment вразливість?', type: 'MULTIPLE_CHOICE', correctOrder: 'dmv2-17-C', blocks: [{ id: 'dmv2-17-A', text: 'A. Відправка великих JSON об\'єктів' }, { id: 'dmv2-17-B', text: 'B. SQL Injection через POST тіло' }, { id: 'dmv2-17-C', text: 'C. Автоматичне прив\'язування всіх полів запиту до моделі — зловмисник може змінити role: "ADMIN" якщо немає whitelist' }, { id: 'dmv2-17-D', text: 'D. Buffer overflow у Node.js' }] },
  { title: 'Рейд 38: Безпечний redirect', description: 'Склади Express redirect з захистом від Open Redirect:', type: 'SORTING', correctOrder: 'dmv2-18-1,dmv2-18-2,dmv2-18-3,dmv2-18-4', blocks: [{ id: 'dmv2-18-1', text: 'const ALLOWED_HOSTS = ["myapp.com"];' }, { id: 'dmv2-18-2', text: 'const url = new URL(req.query.redirect);' }, { id: 'dmv2-18-3', text: 'if (!ALLOWED_HOSTS.includes(url.hostname)) return res.status(400).send("Invalid redirect");' }, { id: 'dmv2-18-4', text: 'res.redirect(req.query.redirect);' }] },
  { title: 'Рейд 39: JWT none algorithm', description: 'Яка критична вразливість пов\'язана з JWT алгоритмом "none"?', type: 'MULTIPLE_CHOICE', correctOrder: 'dmv2-19-B', blocks: [{ id: 'dmv2-19-A', text: 'A. Зменшена швидкість верифікації' }, { id: 'dmv2-19-B', text: 'B. Підпис повністю ігнорується — зловмисник може підробити будь-який payload без секрету' }, { id: 'dmv2-19-C', text: 'C. none алгоритм не підтримується бібліотеками' }, { id: 'dmv2-19-D', text: 'D. Тільки HTTPS захищає від цього' }] },
  { title: 'Рейд 40: Dependency audit', description: 'Яка команда перевіряє npm залежності на відомі вразливості?', type: 'MULTIPLE_CHOICE', correctOrder: 'dmv2-20-A', blocks: [{ id: 'dmv2-20-A', text: 'A. npm audit (або bun audit)' }, { id: 'dmv2-20-B', text: 'B. npm check-security' }, { id: 'dmv2-20-C', text: 'C. npm scan --vulnerabilities' }, { id: 'dmv2-20-D', text: 'D. node --security-check' }] },
  { title: 'Рейд 41: Serialization attack', description: 'Чому небезпечно десеріалізувати JSON від клієнта без валідації?', type: 'MULTIPLE_CHOICE', correctOrder: 'dmv2-21-D', blocks: [{ id: 'dmv2-21-A', text: 'A. JSON.parse завжди безпечний' }, { id: 'dmv2-21-B', text: 'B. JSON не підтримує складні типи' }, { id: 'dmv2-21-C', text: 'C. Сервер може зависнути від великого JSON' }, { id: 'dmv2-21-D', text: 'D. Зловмисник може передати prototype pollution payload або неочікувані типи що ламають логіку' }] },
  { title: 'Рейд 42: Prototype Pollution', description: 'Склади захист від prototype pollution при merge об\'єктів:', type: 'SORTING', correctOrder: 'dmv2-22-1,dmv2-22-2,dmv2-22-3', blocks: [{ id: 'dmv2-22-1', text: 'function safeMerge(target, source) {' }, { id: 'dmv2-22-2', text: '  for (const key of Object.keys(source)) {' }, { id: 'dmv2-22-3', text: '    if (key === "__proto__" || key === "constructor") continue;\n    target[key] = source[key]; } }' }] },
  { title: 'Рейд 43: Log Injection', description: 'Як запобігти Log Injection (CRLF Injection) при логуванні вводу користувача?', type: 'MULTIPLE_CHOICE', correctOrder: 'dmv2-23-C', blocks: [{ id: 'dmv2-23-A', text: 'A. Логувати тільки GET запити' }, { id: 'dmv2-23-B', text: 'B. Вимкнути логування вводу' }, { id: 'dmv2-23-C', text: 'C. Санітизувати input перед логуванням: видалити \n, \r, та екранувати спецсимволи' }, { id: 'dmv2-23-D', text: 'D. Використовувати console.log замість файлових логів' }] },
  { title: 'Рейд 44: Роль перевірка', description: 'Склади middleware перевірки ролі ADMIN:', type: 'SORTING', correctOrder: 'dmv2-24-1,dmv2-24-2,dmv2-24-3,dmv2-24-4', blocks: [{ id: 'dmv2-24-1', text: 'export const requireAdmin = (req: AuthenticatedRequest, res: Response, next: NextFunction) => {' }, { id: 'dmv2-24-2', text: '  if (req.user?.role !== "ADMIN") {' }, { id: 'dmv2-24-3', text: '    return res.status(403).json({ error: "Доступ заборонено" });' }, { id: 'dmv2-24-4', text: '  }\n  next();\n};' }] },
  { title: 'Рейд 45: Security misconfiguration', description: 'Яка помилка є найпоширенішою Security Misconfiguration?', type: 'MULTIPLE_CHOICE', correctOrder: 'dmv2-25-B', blocks: [{ id: 'dmv2-25-A', text: 'A. Використання TypeScript замість JavaScript' }, { id: 'dmv2-25-B', text: 'B. Залишення debug endpoints (/swagger, /graphql, stack traces) відкритими у продакшні' }, { id: 'dmv2-25-C', text: 'C. Відсутність CSS анімацій' }, { id: 'dmv2-25-D', text: 'D. Неправильні назви змінних' }] },
  { title: 'Рейд 46: Token blacklist', description: 'Як реалізувати logout з JWT без сесій?', type: 'MULTIPLE_CHOICE', correctOrder: 'dmv2-26-D', blocks: [{ id: 'dmv2-26-A', text: 'A. Видалити токен з localStorage — достатньо' }, { id: 'dmv2-26-B', text: 'B. JWT не підтримує logout' }, { id: 'dmv2-26-C', text: 'C. Змінити JWT_SECRET — всі токени стануть невалідними' }, { id: 'dmv2-26-D', text: 'D. Зберігати jti (JWT ID) у Redis blacklist і перевіряти при кожному запиті' }] },
  { title: 'Рейд 47: Snyk та SCA', description: 'Що таке SCA (Software Composition Analysis) у контексті безпеки?', type: 'MULTIPLE_CHOICE', correctOrder: 'dmv2-27-A', blocks: [{ id: 'dmv2-27-A', text: 'A. Аналіз залежностей (npm packages) на відомі CVE вразливості та ліцензійні проблеми' }, { id: 'dmv2-27-B', text: 'B. Статичний аналіз власного коду' }, { id: 'dmv2-27-C', text: 'C. Аналіз мережевого трафіку' }, { id: 'dmv2-27-D', text: 'D. Сканування Docker образів' }] },
  { title: 'Рейд 48: HSTS заголовок', description: 'Що робить HTTP Strict-Transport-Security (HSTS) заголовок?', type: 'MULTIPLE_CHOICE', correctOrder: 'dmv2-28-C', blocks: [{ id: 'dmv2-28-A', text: 'A. Блокує HTTP запити на сервері' }, { id: 'dmv2-28-B', text: 'B. Шифрує cookies' }, { id: 'dmv2-28-C', text: 'C. Вказує браузеру завжди використовувати HTTPS для цього домену — захист від downgrade attacks' }, { id: 'dmv2-28-D', text: 'D. Автоматично оновлює SSL сертифікат' }] },
  { title: 'Рейд 49: Supply Chain Attack', description: 'Що таке Supply Chain Attack (наприклад, event-stream інцидент)?', type: 'MULTIPLE_CHOICE', correctOrder: 'dmv2-29-B', blocks: [{ id: 'dmv2-29-A', text: 'A. DDoS на npm реєстр' }, { id: 'dmv2-29-B', text: 'B. Компрометація залежності що використовується тисячами проектів — шкідливий код потрапляє через довірену бібліотеку' }, { id: 'dmv2-29-C', text: 'C. Крадіжка npm токенів' }, { id: 'dmv2-29-D', text: 'D. Man-in-the-middle при npm install' }] },
  { title: 'Рейд 50: Фінальний бій Демона', description: 'Назви принцип Defense in Depth у кібербезпеці:', type: 'MULTIPLE_CHOICE', correctOrder: 'dmv2-30-D', blocks: [{ id: 'dmv2-30-A', text: 'A. Один потужний firewall замість багатьох' }, { id: 'dmv2-30-B', text: 'B. Шифрування всього трафіку' }, { id: 'dmv2-30-C', text: 'C. Zero-day захист' }, { id: 'dmv2-30-D', text: 'D. Кілька рівнів захисту — якщо один зламано, наступний зупиняє атаку (Auth + Rate Limit + Input Validation + WAF + Monitoring)' }] },
];

// ─────────────────────────────────────────────────────────────────
// ГОЛОВНА ФУНКЦІЯ
// ─────────────────────────────────────────────────────────────────
async function main() {
  console.log('Додаємо 30 нових питань до кожного боса (v2)...\n');

  const bossMap: Record<string, PuzzleData[]> = {
    'Зелений Жнець (Memory Leak)': resolveIds(reaper30),
    'Уроборос (Infinite Loop)': resolveIds(dragon30),
    'Червоний Демон (Kernel Panic)': resolveIds(demon30),
  };

  try {
    for (const [bossName, puzzles] of Object.entries(bossMap)) {
      const boss = await prisma.boss.findFirst({ where: { name: bossName, universityId: null } });
      if (!boss) { console.error(`Боса шаблона "${bossName}" не знайдено.`); continue; }

      const before = await prisma.puzzle.count({ where: { bossId: boss.id } });
      let added = 0;

      for (const puzzleData of puzzles) {
        const exists = await prisma.puzzle.findFirst({ where: { bossId: boss.id, title: puzzleData.title } });
        if (exists) { console.log(`  Вже є: "${puzzleData.title}"`); continue; }

        await prisma.puzzle.create({
          data: {
            title: puzzleData.title,
            description: puzzleData.description,
            type: puzzleData.type,
            bossId: boss.id,
            correctOrder: puzzleData.correctOrder,
            blocks: { create: puzzleData.blocks },
          },
        });
        added++;
      }

      const after = await prisma.puzzle.count({ where: { bossId: boss.id } });
      console.log(`${bossName}: ${before} → ${after} питань (додано ${added})`);
    }
    console.log('\nГотово!');
  } catch (err) {
    console.error('Помилка:', err);
  } finally {
    await prisma.$disconnect();
  }
}

main();
